server:
  port: 9190

spring:
  application:
    name: inventory-service

  config:
    import: configserver:${CONFIG_SERVER_BASE_URL:http://config.172.20.136.101.sslip.io}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/inventory_db}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

  output:
    ansi:
      enabled: always

rabbitmq:
  create-resource-queue: create-inventory-resource-queue
  delete-resource-queue: delete-inventory-resource-queue
  change-resource-status-queue: change-inventory-resource-status-queue

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.context: DEBUG